[client]
showErrorDetails = false

[toolbar]
show = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B00"          # Naranjo de construcción para los controles
backgroundColor = "#121212"      # Fondo gris oscuro elegante
secondaryBackgroundColor = "#1E1E1E" # Tarjetas y menú lateral gris oscuro
textColor = "#FFFFFF"            # Texto blanco nítido
font = "sans serif"
